create database retail_store;
use retail_store;
alter table data rename column `ï»¿Transaction ID` to `Transaction ID`;
select * from data;
alter table data modify column `Transaction Date` date;
select * from Data;
select Count(*) from data;
alter table data rename to retail_sales;
describe retail_sales;
ALTER TABLE retail_sales RENAME COLUMN `Sum of Price Per Unit` TO price_per_unit;
ALTER TABLE retail_sales RENAME COLUMN `Sum of Quantity` TO quantity;
ALTER TABLE retail_sales RENAME COLUMN `Sum of Total Spent` TO total_spent;
ALTER TABLE retail_sales RENAME COLUMN `Customer ID` TO Customer_ID;
ALTER TABLE retail_sales RENAME COLUMN `Transaction ID` TO Transaction_ID;
select * from retail_sales;
alter table retail_sales rename column `Transaction Date` to Transaction_Date;
alter table retail_sales rename column `Payment Method` to Payment_Method;
alter table retail_sales rename column `Discount Applied` to Discount_Applied;
select Count(*) from retail_sales;
select min(transaction_date) as earliest_date,max(transaction_date) as latest_date from retail_sales; 
select category,round(sum(total_spent),2) as Total_revenue from  retail_sales group by category order by total_revenue desc;
select Location,round(sum(total_spent),2) as  Total_Revenue from retail_sales group by Location; 
select Payment_method,round(sum(total_spent),2) as Total_Revenue,count(*) as NO_Of_Transactions from retail_sales group by Payment_Method order by Total_Revenue Desc;
select item,round(sum(total_spent),2) as Total_Revenue from retail_sales where item != 'Unknown Item' group by item order by Total_Revenue desc limit 10;
select date_format(Transaction_date,'%Y-%m')as month,round(sum(total_spent)) as total_revenue from retail_sales group by month order by month;
select Discount_applied,round(avg(total_spent),2) as avg_transaction_value,count(*) as no_of_transactions from retail_sales group by discount_applied;
select category,round(sum(total_spent),2) as Total_Revenue from retail_sales group by category order by Total_revenue desc;